"use strict";
/* -------------------------------------------------------
    EXPRESS - Personnel API
------------------------------------------------------- */

// Authentication Control Middleware:

const Token = require("../models/token.model");

module.exports = async (req, res, next) => {
  // Authorization: Token ...tokenKey...
  // Authorization: ApiKey ...tokenKey...
  // Authorization: Bearer ...tokenKey...
  // Authorization: Auth ...tokenKey...
  // Authorization: X-API-KEY ...tokenKey...
  // Authorization: x-auth-token ...tokenKey...

  // Get Token from Headers:
  const auth = req.headers?.authorization || null; // Token ...tokenKey...
};

/* ------------------------------------------------------- */
